# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
"""Resolve the Python dependencies needed by the SDK development image.

Run this from a manifest checkout containing all five component repositories.
The public Docker build uses only the checked-in output in the SDK root repo.
"""

import argparse
import difflib
import hashlib
import subprocess
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    try:
        import tomli as tomllib
    except ModuleNotFoundError:
        tomllib = None


COMPONENTS = (
    "emulation-layer",
    "model-converter",
    "scenario-runner",
    "vgf-lib",
    "workload-lib",
)


def collect_requirements(sdk_root: Path) -> tuple[list[str], str]:
    paths = [sdk_root / "pyproject.toml"] + [
        sdk_root / "sw" / name / "pyproject.toml" for name in COMPONENTS
    ]
    missing = [path for path in paths if not path.is_file()]
    if missing:
        raise ValueError(
            "Docker requirements need the complete manifest checkout; missing: "
            + ", ".join(str(path) for path in missing)
        )

    requirements = set()
    for path in paths:
        with path.open("rb") as source:
            project = tomllib.load(source)
        requirements.update(project.get("project", {}).get("dependencies", []))
        for extra in (
            project.get("project", {}).get("optional-dependencies", {}).values()
        ):
            requirements.update(extra)
        requirements.update(project.get("build-system", {}).get("requires", []))
        for group in project.get("dependency-groups", {}).values():
            requirements.update(group)

    ordered = sorted(requirements, key=str.casefold)
    digest = hashlib.sha256("\n".join(ordered).encode("utf-8")).hexdigest()
    return ordered, digest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sdk-root", type=Path, default=Path(__file__).resolve().parents[1]
    )
    parser.add_argument("--uv", default="uv", help="uv executable to use")
    parser.add_argument(
        "--python", default="3.12", help="Python 3.12 interpreter used by uv"
    )
    parser.add_argument(
        "--check", action="store_true", help="resolve and compare the complete output"
    )
    args = parser.parse_args()
    if tomllib is None:
        # A direct invocation on clean Python 3.10 needs a TOML parser. Use the
        # same uv executable that will resolve the Docker requirements below.
        return subprocess.call(
            [
                args.uv,
                "run",
                "--no-project",
                "--isolated",
                "--with",
                "tomli==2.4.1",
                "--python",
                sys.executable,
                str(Path(__file__).resolve()),
                *sys.argv[1:],
            ]
        )
    sdk_root = args.sdk_root.resolve()
    output = sdk_root / "docker" / "requirements.txt"

    try:
        requirements, digest = collect_requirements(sdk_root)
    except ValueError as error:
        parser.error(str(error))

    command = [
        args.uv,
        "pip",
        "compile",
        "-",
        "--python-version",
        "3.12",
        "--python",
        args.python,
        "--python-platform",
        "linux",
        "--no-header",
        "--no-annotate",
    ]
    result = subprocess.run(
        command,
        input="\n".join(requirements) + "\n",
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode:
        print(result.stderr, file=sys.stderr)
        return result.returncode

    header = (
        "# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates "
        "<open-source-office@arm.com>\n"
        "# SPDX-"
        "License-Identifier: Apache-2.0\n"
        "# Generated by docker/update_requirements.py\n"
        "# Python 3.12 on Linux; includes the SDK and all five components.\n"
        f"# Input-SHA256: {digest}\n"
        "# Regenerate from a complete manifest checkout after dependency changes.\n\n"
    )
    generated = header + result.stdout
    if args.check:
        existing = output.read_text(encoding="utf-8") if output.is_file() else ""
        if existing != generated:
            print(
                f"{output} is stale or differs from the resolved dependencies. "
                "Run this script without --check in the complete manifest "
                "checkout and commit the updated file.",
                file=sys.stderr,
            )
            sys.stderr.writelines(
                difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    generated.splitlines(keepends=True),
                    fromfile=str(output),
                    tofile="freshly resolved requirements",
                )
            )
            return 1
        print(f"{output} matches the resolved component dependencies")
        return 0

    output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {output} from {len(requirements)} direct requirements")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
